---
- name: Uninstall Apache
  apt:
    name: "{{ item }}"
    autoremove: yes
    state: absent
    force: true
  loop:
    - apache2
  notify: stop apache

- name: Install NGINX
  apt:
    name: nginx
    state: present
  notify: restart nginx

- name: "Ensure {{ nginx__config_path }}/conf.d directory exists"
  file:
    path: "{{ nginx__config_path }}/conf.d"
    state: directory
    mode: '0755'

- name: "Ensure {{ nginx__config_path }}/sites-available directory exists"
  file:
    path: "{{ nginx__config_path }}/sites-available"
    state: directory
    mode: '0755'

- name: "Ensure {{ nginx__config_path }}/sites-enabled directory exists"
  file:
    path: "{{ nginx__config_path }}/sites-enabled"
    state: directory
    mode: '0755'

- name: Deploy main NGINX configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx__config_path }}/nginx.conf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart nginx

- name: Copy page default NGINX 
  template:
    src: index.html
    dest: "{{ nginx__deploy_path }}/index.html"
  notify: restart nginx

- name: Deploy NGINX custom global configuration snippet
  template:
    src: 99-global-custom.conf.j2
    dest: "{{ nginx__config_path }}/conf.d/99-global-custom.conf"
    owner: root
    group: root
    mode: '0644'
  when: nginx__global_settings is defined and nginx__global_settings | length > 0
  notify: restart nginx