---
- name: Configure ondrej/php apt repository
  apt_repository:
    repo: "{{ php__apt_repo }}"
    state: present
    update_cache: yes

- name: Install php-fpm {{ php__version }} and dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php{{ php__version }}
    - php{{ php__version }}-fpm
    - php{{ php__version }}-common
    - php{{ php__version }}-zip
    - php{{ php__version }}-pgsql
    - php{{ php__version }}-curl
    - php{{ php__version }}-xml
    - php{{ php__version }}-xmlrpc
    - php{{ php__version }}-pdo
    - php{{ php__version }}-gd
    - php{{ php__version }}-imagick
    - php{{ php__version }}-ldap
    - php{{ php__version }}-imap
    - php{{ php__version }}-mbstring
    - php{{ php__version }}-intl
    - php{{ php__version }}-cli
    - php{{ php__version }}-tidy
    - php{{ php__version }}-bcmath
    - php{{ php__version }}-opcache
    - php{{ php__version }}-ctype
    - php{{ php__version }}-dom
    - php{{ php__version }}-fileinfo
    - php{{ php__version }}-iconv
    - php{{ php__version }}-phar
    - php{{ php__version }}-simplexml
    - php{{ php__version }}-tokenizer
    - php{{ php__version }}-xmlreader
    - php{{ php__version }}-xmlwriter
  register: php_setup
  notify: restart php-fpm

- name: Create custom PHP settings in conf.d
  template:
    src: php-custom.ini.j2
    dest: "/etc/php/{{ php__version }}/fpm/conf.d/99-custom.ini"
    owner: root
    group: root
    mode: '0644'
    validate: 'php -d display_errors=stderr -r "php_ini_loaded_file();" -c %s'
  notify: restart php-fpm

- name: Create custom PHP-FPM pool settings
  template:
    src: php-fpm-pool-www.conf.j2
    dest: "/etc/php/{{ php__version }}/fpm/pool.d/99-www-custom.conf"
    owner: root
    group: root
    mode: '0644'
    validate: '/usr/sbin/php-fpm{{ php__version }} -t -y %s'
  notify: restart php-fpm