---

- name: "Playbook to Add Key to EC2 Instances"
  hosts: appservers
  vars:
    - status : "present"
    - key : "~/.ssh/id_rsa.pub"

  tasks:

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{ ansible_user }}"
      state: "{{ status }}"
      key: "{{ lookup('file', '{{ key }}')}}"