- hosts: ieducar
  become: true

  roles:
    - role: common
      tags: [common]

    - role: postgresql
      tags: [postgresql]

    - role: redis-server
      tags: [redis-server]

    - role: php-fpm
      tags: [php-fpm]

    - role: nginx
      tags: [nginx]

    - role: i-educar
      become_user: "{{ app__run_user }}"
      tags: [i-educar]

    - role: i-educar-reports-package
      become_user: "{{ app__run_user }}"
      tags: [i-educar-reports-package]

    - role: i-educar-educacenso-package
      become_user: "{{ app__run_user }}"
      tags: [i-educar-educacenso-package]