# Variables specific to the staging environment

# Application environment for staging
ieducar_app_env: staging
ieducar_app_debug: true

# Database configuration for staging
ieducar_db_host: 127.0.0.1
ieducar_db_port: 5432
ieducar_db_username: ieducar
ieducar_db_password: ieducar
ieducar_db_database: ieducar_staging