# Variables specific to the production environment

# Enable custom domain for the NGINX site
ieducar__with_domain: true

# Public domain name to be used in NGINX configuration
ieducar__name_domain: "ieducar.net.br"

# Enable SSL for the site
ieducar__use_ssl: true

# Use Let's Encrypt to generate and manage the SSL certificate
ieducar__use_letsencrypt: true

# Let's Encrypt configuration
letsencrypt__ssl: true
letsencrypt__cert_name: "ieducar.net.br"

# Optional: override certificate paths if not using Let's Encrypt
ieducar__ssl_certificate_path: "/etc/ssl/certs/fullchain.pem"
ieducar__ssl_certificate_key_path: "/etc/ssl/private/privkey.pem"
