---
- name: Ensure all configured locales are present
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ system__locales }}"

- name: Configure locale and language
  shell: dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG={{ system__language }} LANGUAGE={{ system__language }}
  register: locale__result
  changed_when: "locale__result.changed == true"