# roles/i-educar/defaults/main.yml

# If true, automatically confirm composer install prompts
ieducar__composer_allow_prompt: false

# Path to the .env file for i-Educar
env_path: "{{ ieducar__base_path }}/.env"

# List of .env keys to read and use for configuration
values:
  - APP_ENV
  - APP_DEBUG
  - DB_HOST
  - DB_PORT
  - DB_DATABASE
  - DB_USERNAME
  - DB_PASSWORD
  - APP_URL
  - APP_KEY
  - FILESYSTEM_DRIVER